// This file is kept for backward compatibility
// For new components, prefer direct imports like:
// import { faIconName } from '@fortawesome/free-solid-svg-icons';

import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faMagnifyingGlass,
  faBagShopping,
  faBars,
  faChevronDown,
  faChevronUp,
  faEnvelope,
  faPhone,
  faLocationDot,
  faFilter,
  faStar,
  faStarHalfStroke,
  faHeart,
  faShare,
  faArrowLeft,
  faArrowRight,
  faFolder,
  faFolderOpen,
  faPlus,
  faMinus,
  faHouse,
  faUser,
  faTrashCan,
  faPenToSquare,
  faEye,
  faCheck,
  faXmark,
  faLeaf,
  faHandshakeAngle,
  faGem,
  faCartShopping,
  faTag,
  faTags,
  faList,
  faUsers,
  faUserPlus,
  faCalendar,
  faCalendarDays,
  faImage,
  faImages,
  faUpload,
  faDownload,
  faGear,
  faGears,
  faClipboard,
  faClipboardList,
  faBox,
  faBoxes,
  faQuestion,
  faCircleQuestion,
  faExclamation,
  faCircleExclamation,
  faCircleInfo,
  faAngleRight,
  faAngleLeft,
  faAngleDown,
  faAngleUp,
  faPaperPlane,
  faComments
} from '@fortawesome/free-solid-svg-icons';

import { 
  faFacebookF, 
  faInstagram, 
  faPinterestP, 
  faWhatsapp,
  faTwitter,
  faYoutube,
  faTiktok
} from '@fortawesome/free-brands-svg-icons';

import {
  faStar as farStar,
  faHeart as farHeart,
  faUser as farUser,
  faCircle as farCircle,
  faComment as farComment
} from '@fortawesome/free-regular-svg-icons';

// Add icons to the library
library.add(
  // Solid icons
  faMagnifyingGlass,
  faBagShopping,
  faBars,
  faChevronDown,
  faChevronUp,
  faEnvelope,
  faPhone,
  faLocationDot,
  faFilter,
  faStar,
  faStarHalfStroke,
  faHeart,
  faShare,
  faArrowLeft,
  faArrowRight,
  faFolder,
  faFolderOpen,
  faPlus,
  faMinus,
  faHouse,
  faUser,
  faTrashCan,
  faPenToSquare,
  faEye,
  faCheck,
  faXmark,
  faLeaf,
  faHandshakeAngle,
  faGem,
  faCartShopping,
  faTag,
  faTags,
  faList,
  faUsers,
  faUserPlus,
  faCalendar,
  faCalendarDays,
  faImage,
  faImages,
  faUpload,
  faDownload,
  faGear,
  faGears,
  faClipboard,
  faClipboardList,
  faBox,
  faBoxes,
  faQuestion,
  faCircleQuestion,
  faExclamation,
  faCircleExclamation,
  faCircleInfo,
  faAngleRight,
  faAngleLeft,
  faAngleDown,
  faAngleUp,
  faPaperPlane,
  faComments,
  
  // Brand icons
  faFacebookF,
  faInstagram,
  faPinterestP,
  faWhatsapp,
  faTwitter,
  faYoutube,
  faTiktok,
  
  // Regular icons
  farStar,
  farHeart,
  farUser,
  farCircle,
  farComment
);

// Export the icons for direct use
export {
  faMagnifyingGlass,
  faBagShopping,
  faBars,
  faChevronDown,
  faChevronUp,
  faEnvelope,
  faPhone,
  faLocationDot,
  faFilter,
  faStar,
  faStarHalfStroke,
  faHeart,
  faShare,
  faArrowLeft,
  faArrowRight,
  faFolder,
  faFolderOpen,
  faPlus,
  faMinus,
  faHouse,
  faUser,
  faTrashCan,
  faPenToSquare,
  faEye,
  faCheck,
  faXmark,
  faLeaf,
  faHandshakeAngle,
  faGem,
  faCartShopping,
  faTag,
  faTags,
  faList,
  faUsers,
  faUserPlus,
  faCalendar,
  faCalendarDays,
  faImage,
  faImages,
  faUpload,
  faDownload,
  faGear,
  faGears,
  faClipboard,
  faClipboardList,
  faBox,
  faBoxes,
  faQuestion,
  faCircleQuestion,
  faExclamation,
  faCircleExclamation,
  faCircleInfo,
  faAngleRight,
  faAngleLeft,
  faAngleDown,
  faAngleUp,
  faPaperPlane,
  faComments,
  
  // Brand icons
  faFacebookF, 
  faInstagram, 
  faPinterestP, 
  faWhatsapp,
  faTwitter,
  faYoutube,
  faTiktok,
  
  // Regular icons
  farStar,
  farHeart,
  farUser,
  farCircle,
  farComment
};